SHOW TABLES;

DROP TABLE IF EXISTS Usuario;
CREATE TABLE Usuario (
	id INT NOT NULL AUTO_INCREMENT,
	nome VARCHAR(200) NOT NULL,
	login VARCHAR(20) NOT NULL,
	senha VARCHAR(200) NOT NULL,
	PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS Produto (
	id INT NOT NULL AUTO_INCREMENT,
	nome VARCHAR(200) NOT NULL,
	preco_custo FLOAT NOT NULL,
	preco_venda FLOAT NOT NULL,
	quantidade INT NOT NULL,
	PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS Fornecedor (
    id INT NOT NULL AUTO_INCREMENT,
    cnpj VARCHAR(18) NOT NULL UNIQUE,
    nome VARCHAR(200) NOT NULL,
    cep INT(8) NOT NULL,
    endereco VARCHAR(200) NOT NULL,
    numero VARCHAR(10),
    complemento VARCHAR(10),
    cidade VARCHAR(60),
    estado VARCHAR(2),
    
    PRIMARY KEY (id)
);